name: book_app_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  path_provider: ^2.1.0
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^22.2.8
  easy_localization: ^3.0.2
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  provider: ^6.0.5
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/tr/
